### PR TITLE
Add Recommendation container and first Recommendation component

### PR DESCRIPTION
**Pull request by DavidMatalik**
Peek 2021-06-09 12-51

### CODE REVIEW

**Review by RichStone — COMMENTED** [review]
Like! (including the very transformed new Rich :muscle: )

You could see if you wanna spend like one pomodoro on these improvements in a separate PR:

(in this priority)

* rename RecommendationComponent (it's already clear that it's a Component, since it's in the Component folder ;). I'd go for RecommendationDetail or something.
* it'd be a bit better if the photo could be also centered on bigger screens, between the detail border and the text 
* (optional) make the `components` folder a `containers` folder (this could be come a bigger refactoring and should be its own PR). Make sure everything still works. Create a `components` folder and move RecommendationDetail and ProjectDetailModal in there (ProjectDetailModal could also be just ProjectDetail, I think). Good luck! :stuck_out_tongue:

**Review by RichStone — APPROVED** [review]

**Comment by RichStone** [comment]
why did the package lock json end up in this PR? Usually, if you don't install any new stuff to your app in the package.json, the lock json should be unchanged

**Comment by DavidMatalik** [comment]
> * it'd be a bit better if the photo could be also centered on bigger screens, between the detail border and the text

That is already kind of implemented. If I had made the screen bigger in the gif you would have seen it. It gets not centered... but the distance to the left border gets bigger and bigger.

**Comment by DavidMatalik** [comment]
> why did the package lock json end up in this PR? Usually, if you don't install any new stuff to your app in the package.json, the lock json should be unchanged

Man, that is a pretty good question... Maybe it came because you installed the whole thing locally to work initially with it? And I cherry picked something from your repo? Maybe there was a difference in the json-lock? You know one difference is that `lockFileVersion` changed from 2 to 1. Maybe you had an older npm version or something?

So what to do about it?

**Comment by RichStone** [comment]
> > why did the package lock json end up in this PR? Usually, if you don't install any new stuff to your app in the package.json, the lock json should be unchanged
> 
> Man, that is a pretty good question... Maybe it came because you installed the whole thing locally to work initially with it? And I cherry picked something from your repo? Maybe there was a difference in the json-lock? You know one difference is that `lockFileVersion` changed from 2 to 1. Maybe you had an older npm version or something?
> 
> So what to do about it?

Ok, yeah that's true, stuff might have changed order and all... You should just leave it out from the PR since it's not really related to the changes that need to be done for the PR

**Comment by RichStone** [comment]
> > * it'd be a bit better if the photo could be also centered on bigger screens, between the detail border and the text
> 
> That is already kind of implemented. If I had made the screen bigger in the gif you would have seen it. It gets not centered... but the distance to the left border gets bigger and bigger.

great! I think, you can take out the package lock json and merge this PR :)

**Comment by RichStone** [comment]
I think this one is good to go ;)

**Comment by DavidMatalik** [comment]
> I think this one is good to go ;)

Nearly: I add new lines at the end of two files and also write some stuff the best way I know. Because you said it's a good approach to write immediately good code and make notes for refactoring related stuff in another PR.

**Pull request merged**
