### PR TITLE
Change Padding of Polaroid and practice fixup + rebase again

### PR DESCRIPTION
**Pull request by DavidMatalik**
And we also have a conflict now! =) Because the commit history is kind of similar but still different, right?

### CODE REVIEW

**Comment by RichStone** [comment]
I think the issue is that you didn't work on the latest version of the main branch :O)

What you'd need to do is to get your current `polaroid` branch version up to date with the `main` branch.

You can do it by doing this from your polaroid branch:

```shell
$ git fetch origin main
$ git rebase origin/main
```

You should then get the conflict locally. Resolve it by fixing this locally:

```
<<<<<<< polaroid
  padding-bottom: 15px;
=======
  padding-bottom: 30px;
>>>>>>> main
```

and commiting. And then force push again to your polaroid branch.

**Comment by DavidMatalik** [comment]
> I think the issue is that you didn't work on the latest version of the main branch :O)
> 
> What you'd need to do is to get your current `polaroid` branch version up to date with the `main` branch.
> 
> You can do it by doing this from your polaroid branch:
> 
> ```shell
> $ git fetch origin main
> $ git rebase origin/main
> ```
> 
> You should then get the conflict locally. Resolve it by fixing this locally:
> 
> ```
> <<<<<<< polaroid
>   padding-bottom: 15px;
> =======
>   padding-bottom: 30px;
> >>>>>>> main
> ```
> 
> and commiting. And then force push again to your polaroid branch.

I did it the way you said, but still there is this conflict note. I think it is because I fixuped and rebased the commit "Remove Polaroid effect of images". So the commit  "Remove Polaroid effect of images" is doing something different in polaroid branch and main branch... But yeah when we did the same procedure in adjustStyles branch it didn't show a conflict with main...

**Comment by RichStone** [comment]
> > I think the issue is that you didn't work on the latest version of the main branch :O)
> > What you'd need to do is to get your current `polaroid` branch version up to date with the `main` branch.
> > You can do it by doing this from your polaroid branch:
> > ```shell
> > $ git fetch origin main
> > $ git rebase origin/main
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You should then get the conflict locally. Resolve it by fixing this locally:
> > ```
> > <<<<<<< polaroid
> >   padding-bottom: 15px;
> > =======
> >   padding-bottom: 30px;
> > >>>>>>> main
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and commiting. And then force push again to your polaroid branch.
> 
> I did it the way you said, but still there is this conflict note. I think it is because I fixuped and rebased the commit "Remove Polaroid effect of images". So the commit "Remove Polaroid effect of images" is doing something different in polaroid branch and main branch... But yeah when we did the same procedure in adjustStyles branch it didn't show a conflict with main...

OK, no worries, I'll try this out with your branches on my local

**Comment by RichStone** [comment]
Maybe you are having some whitespacing issues:
whitespace

This worked for me:

```shell
# in my new branch:
git rebase origin/main
 # fix the conflict
git add src/App.scss
git rebase --continue
git push -f
```

Maybe you were missing a step?

You can see it here:

https://github.com/DavidMatalik/portfolio/compare/main...DavidMatalik:polaroid-rich?expand=1

When you rebase onto the main branch, you will also see that your PR gets a bit smaller, because those changes are already inside main ;)

**Comment by RichStone** [comment]
In case something doesn't work, you can just merge here and we could move on for now: 
image

Or we can have a quick chat :)

**Comment by RichStone** [comment]
> Maybe you are having some whitespacing issues:

I think the forked version uses tabs and you used spaces. Configure your VSCode to display this :pray:

**Pull request closed without merging**
